openapi: 3.0.0
info:
  title: FastAPI Full Name API
  version: 1.0.0
  description: API to get full name from first name and last name
servers:
  - url: http://localhost:8000
paths:
  /get_fullname/:
    post:
      summary: Get Full Name
      description: Retrieve full name from first name and last name and return Full name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullName'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  full_name:
                    type: string
      tags:
        - Full Name
components:
  schemas:
    FullName:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
      required:
        - first_name
        - last_name
